version: "3.8"
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "jewlery_db"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION" --max_allowed_packet=256M
    volumes:
      - ./mysql-data:/var/lib/mysql
